# Generated by Django 5.1.4 on 2025-01-22 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, unique=True)),
                ('preco_compra', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.DecimalField(decimal_places=0, max_digits=9)),
                ('imagen', models.ImageField(upload_to='imagens')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.categoria')),
            ],
        ),
    ]
